/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace UnityGive {
  export type CampaignStruct = {
    mongoId: string;
    orgWallet: AddressLike;
    totalGoalAmount: BigNumberish;
    currentAmount: BigNumberish;
    requiredVotes: BigNumberish;
    deadline: BigNumberish;
    isActive: boolean;
    isSuccessful: boolean;
  };

  export type CampaignStructOutput = [
    mongoId: string,
    orgWallet: string,
    totalGoalAmount: bigint,
    currentAmount: bigint,
    requiredVotes: bigint,
    deadline: bigint,
    isActive: boolean,
    isSuccessful: boolean
  ] & {
    mongoId: string;
    orgWallet: string;
    totalGoalAmount: bigint;
    currentAmount: bigint;
    requiredVotes: bigint;
    deadline: bigint;
    isActive: boolean;
    isSuccessful: boolean;
  };

  export type MilestoneStruct = {
    amount: BigNumberish;
    ipfsEvidence: string;
    approvalCount: BigNumberish;
    isApproved: boolean;
    isFunded: boolean;
  };

  export type MilestoneStructOutput = [
    amount: bigint,
    ipfsEvidence: string,
    approvalCount: bigint,
    isApproved: boolean,
    isFunded: boolean
  ] & {
    amount: bigint;
    ipfsEvidence: string;
    approvalCount: bigint;
    isApproved: boolean;
    isFunded: boolean;
  };
}

export interface UnityGiveInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "campaignCount"
      | "campaignMilestones"
      | "campaigns"
      | "cancelCampaign"
      | "donate"
      | "donations"
      | "getCampaign"
      | "getMilestone"
      | "getMilestonesCount"
      | "hasVoted"
      | "isCouncilMember"
      | "refund"
      | "registerCampaign"
      | "topUpCampaign"
      | "uploadProofOfImpact"
      | "voteApproveMilestone"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CampaignCancelled"
      | "CampaignRegistered"
      | "DonationReceived"
      | "FundsReleased"
      | "MilestoneAdded"
      | "MilestoneApproved"
      | "ProofUploaded"
      | "RefundIssued"
      | "Voted"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "campaignCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaignMilestones",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "donate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "donations",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMilestone",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMilestonesCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCouncilMember",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "refund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCampaign",
    values: [
      string,
      AddressLike,
      BigNumberish,
      AddressLike[],
      BigNumberish,
      BigNumberish[],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "topUpCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "uploadProofOfImpact",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "voteApproveMilestone",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "campaignCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignMilestones",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "donations", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMilestonesCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCouncilMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "topUpCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uploadProofOfImpact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteApproveMilestone",
    data: BytesLike
  ): Result;
}

export namespace CampaignCancelledEvent {
  export type InputTuple = [campaignId: BigNumberish];
  export type OutputTuple = [campaignId: bigint];
  export interface OutputObject {
    campaignId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignRegisteredEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    mongoId: string,
    goalAmount: BigNumberish,
    requiredVotes: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    mongoId: string,
    goalAmount: bigint,
    requiredVotes: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    mongoId: string;
    goalAmount: bigint;
    requiredVotes: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DonationReceivedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    donor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [campaignId: bigint, donor: string, amount: bigint];
  export interface OutputObject {
    campaignId: bigint;
    donor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReleasedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    milestoneIndex: BigNumberish,
    orgWallet: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    milestoneIndex: bigint,
    orgWallet: string,
    amount: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    milestoneIndex: bigint;
    orgWallet: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneAddedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    milestoneIndex: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    milestoneIndex: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    milestoneIndex: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneApprovedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    milestoneIndex: BigNumberish
  ];
  export type OutputTuple = [campaignId: bigint, milestoneIndex: bigint];
  export interface OutputObject {
    campaignId: bigint;
    milestoneIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofUploadedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    milestoneIndex: BigNumberish,
    ipfsCID: string
  ];
  export type OutputTuple = [
    campaignId: bigint,
    milestoneIndex: bigint,
    ipfsCID: string
  ];
  export interface OutputObject {
    campaignId: bigint;
    milestoneIndex: bigint;
    ipfsCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundIssuedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    donor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [campaignId: bigint, donor: string, amount: bigint];
  export interface OutputObject {
    campaignId: bigint;
    donor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    milestoneIndex: BigNumberish,
    voter: AddressLike
  ];
  export type OutputTuple = [
    campaignId: bigint,
    milestoneIndex: bigint,
    voter: string
  ];
  export interface OutputObject {
    campaignId: bigint;
    milestoneIndex: bigint;
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface UnityGive extends BaseContract {
  connect(runner?: ContractRunner | null): UnityGive;
  waitForDeployment(): Promise<this>;

  interface: UnityGiveInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  campaignCount: TypedContractMethod<[], [bigint], "view">;

  campaignMilestones: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, bigint, boolean, boolean] & {
        amount: bigint;
        ipfsEvidence: string;
        approvalCount: bigint;
        isApproved: boolean;
        isFunded: boolean;
      }
    ],
    "view"
  >;

  campaigns: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean, boolean] & {
        mongoId: string;
        orgWallet: string;
        totalGoalAmount: bigint;
        currentAmount: bigint;
        requiredVotes: bigint;
        deadline: bigint;
        isActive: boolean;
        isSuccessful: boolean;
      }
    ],
    "view"
  >;

  cancelCampaign: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  donate: TypedContractMethod<[campaignId: BigNumberish], [void], "payable">;

  donations: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getCampaign: TypedContractMethod<
    [campaignId: BigNumberish],
    [UnityGive.CampaignStructOutput],
    "view"
  >;

  getMilestone: TypedContractMethod<
    [campaignId: BigNumberish, milestoneIndex: BigNumberish],
    [UnityGive.MilestoneStructOutput],
    "view"
  >;

  getMilestonesCount: TypedContractMethod<
    [campaignId: BigNumberish],
    [bigint],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [boolean],
    "view"
  >;

  isCouncilMember: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  refund: TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;

  registerCampaign: TypedContractMethod<
    [
      mongoId: string,
      orgWallet: AddressLike,
      goalAmount: BigNumberish,
      councilMembers: AddressLike[],
      requiredVotes: BigNumberish,
      milestoneAmounts: BigNumberish[],
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  topUpCampaign: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "payable"
  >;

  uploadProofOfImpact: TypedContractMethod<
    [campaignId: BigNumberish, milestoneIndex: BigNumberish, ipfsCID: string],
    [void],
    "nonpayable"
  >;

  voteApproveMilestone: TypedContractMethod<
    [campaignId: BigNumberish, milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "campaignCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "campaignMilestones"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, bigint, boolean, boolean] & {
        amount: bigint;
        ipfsEvidence: string;
        approvalCount: bigint;
        isApproved: boolean;
        isFunded: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean, boolean] & {
        mongoId: string;
        orgWallet: string;
        totalGoalAmount: bigint;
        currentAmount: bigint;
        requiredVotes: bigint;
        deadline: bigint;
        isActive: boolean;
        isSuccessful: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelCampaign"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "donate"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "donations"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCampaign"
  ): TypedContractMethod<
    [campaignId: BigNumberish],
    [UnityGive.CampaignStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMilestone"
  ): TypedContractMethod<
    [campaignId: BigNumberish, milestoneIndex: BigNumberish],
    [UnityGive.MilestoneStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMilestonesCount"
  ): TypedContractMethod<[campaignId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isCouncilMember"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerCampaign"
  ): TypedContractMethod<
    [
      mongoId: string,
      orgWallet: AddressLike,
      goalAmount: BigNumberish,
      councilMembers: AddressLike[],
      requiredVotes: BigNumberish,
      milestoneAmounts: BigNumberish[],
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "topUpCampaign"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "uploadProofOfImpact"
  ): TypedContractMethod<
    [campaignId: BigNumberish, milestoneIndex: BigNumberish, ipfsCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "voteApproveMilestone"
  ): TypedContractMethod<
    [campaignId: BigNumberish, milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CampaignCancelled"
  ): TypedContractEvent<
    CampaignCancelledEvent.InputTuple,
    CampaignCancelledEvent.OutputTuple,
    CampaignCancelledEvent.OutputObject
  >;
  getEvent(
    key: "CampaignRegistered"
  ): TypedContractEvent<
    CampaignRegisteredEvent.InputTuple,
    CampaignRegisteredEvent.OutputTuple,
    CampaignRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DonationReceived"
  ): TypedContractEvent<
    DonationReceivedEvent.InputTuple,
    DonationReceivedEvent.OutputTuple,
    DonationReceivedEvent.OutputObject
  >;
  getEvent(
    key: "FundsReleased"
  ): TypedContractEvent<
    FundsReleasedEvent.InputTuple,
    FundsReleasedEvent.OutputTuple,
    FundsReleasedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneAdded"
  ): TypedContractEvent<
    MilestoneAddedEvent.InputTuple,
    MilestoneAddedEvent.OutputTuple,
    MilestoneAddedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneApproved"
  ): TypedContractEvent<
    MilestoneApprovedEvent.InputTuple,
    MilestoneApprovedEvent.OutputTuple,
    MilestoneApprovedEvent.OutputObject
  >;
  getEvent(
    key: "ProofUploaded"
  ): TypedContractEvent<
    ProofUploadedEvent.InputTuple,
    ProofUploadedEvent.OutputTuple,
    ProofUploadedEvent.OutputObject
  >;
  getEvent(
    key: "RefundIssued"
  ): TypedContractEvent<
    RefundIssuedEvent.InputTuple,
    RefundIssuedEvent.OutputTuple,
    RefundIssuedEvent.OutputObject
  >;
  getEvent(
    key: "Voted"
  ): TypedContractEvent<
    VotedEvent.InputTuple,
    VotedEvent.OutputTuple,
    VotedEvent.OutputObject
  >;

  filters: {
    "CampaignCancelled(uint256)": TypedContractEvent<
      CampaignCancelledEvent.InputTuple,
      CampaignCancelledEvent.OutputTuple,
      CampaignCancelledEvent.OutputObject
    >;
    CampaignCancelled: TypedContractEvent<
      CampaignCancelledEvent.InputTuple,
      CampaignCancelledEvent.OutputTuple,
      CampaignCancelledEvent.OutputObject
    >;

    "CampaignRegistered(uint256,string,uint256,uint256)": TypedContractEvent<
      CampaignRegisteredEvent.InputTuple,
      CampaignRegisteredEvent.OutputTuple,
      CampaignRegisteredEvent.OutputObject
    >;
    CampaignRegistered: TypedContractEvent<
      CampaignRegisteredEvent.InputTuple,
      CampaignRegisteredEvent.OutputTuple,
      CampaignRegisteredEvent.OutputObject
    >;

    "DonationReceived(uint256,address,uint256)": TypedContractEvent<
      DonationReceivedEvent.InputTuple,
      DonationReceivedEvent.OutputTuple,
      DonationReceivedEvent.OutputObject
    >;
    DonationReceived: TypedContractEvent<
      DonationReceivedEvent.InputTuple,
      DonationReceivedEvent.OutputTuple,
      DonationReceivedEvent.OutputObject
    >;

    "FundsReleased(uint256,uint256,address,uint256)": TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
    FundsReleased: TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;

    "MilestoneAdded(uint256,uint256,uint256)": TypedContractEvent<
      MilestoneAddedEvent.InputTuple,
      MilestoneAddedEvent.OutputTuple,
      MilestoneAddedEvent.OutputObject
    >;
    MilestoneAdded: TypedContractEvent<
      MilestoneAddedEvent.InputTuple,
      MilestoneAddedEvent.OutputTuple,
      MilestoneAddedEvent.OutputObject
    >;

    "MilestoneApproved(uint256,uint256)": TypedContractEvent<
      MilestoneApprovedEvent.InputTuple,
      MilestoneApprovedEvent.OutputTuple,
      MilestoneApprovedEvent.OutputObject
    >;
    MilestoneApproved: TypedContractEvent<
      MilestoneApprovedEvent.InputTuple,
      MilestoneApprovedEvent.OutputTuple,
      MilestoneApprovedEvent.OutputObject
    >;

    "ProofUploaded(uint256,uint256,string)": TypedContractEvent<
      ProofUploadedEvent.InputTuple,
      ProofUploadedEvent.OutputTuple,
      ProofUploadedEvent.OutputObject
    >;
    ProofUploaded: TypedContractEvent<
      ProofUploadedEvent.InputTuple,
      ProofUploadedEvent.OutputTuple,
      ProofUploadedEvent.OutputObject
    >;

    "RefundIssued(uint256,address,uint256)": TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;
    RefundIssued: TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;

    "Voted(uint256,uint256,address)": TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
    Voted: TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
  };
}
